version: "3.3"

services:
    postgres:
        image: postgres:13
        enviroment:
            - POSTGRES_DB=my_store
            - POSTGRES_USER=angel
            - POSTGRES_PASS=admin
        ports:
            - 5432:5432
